branch-defaults:
  master:
    environment: staging
    group_suffix: null
global:
  application_name: vela-ahunter-test40
  branch: null
  default_ec2_keyname: vela-ahunter-test40
  default_platform: Node.js
  default_region: us-west-1
  profile: null
  repository: null
  sc: git
